In [9]:
import numpy as np

li = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

print(li*2) # -> list will duplicate element
print(arr*2) # -> numpy array multiply all the element

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [7]:
import numpy as np

arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(type(arr)) #ndarray -> n dimensial array
print(arr)
print(arr[0][0]) #-> 0 row , 0 column -> 1
print(arr[1][2]) #-> 1 row , 2 column -> 6

alpha = np.array([
    ["A" , "B" , "C" , "D" , "E"],
    ["F" , "G" , "H" , "I" , "J"],
    ["K" , "L" , "M" , "N" , "O"],
    ["P" , "Q" , "R" , "S" , "T"],
    ["U" , "V" , "W" , "X" , "Y"]
])

print(alpha[1][2] + alpha[0][4] + alpha[3][4]) # -> HET
print(alpha[1,2] + alpha[0,4] + alpha[3,4]) # -> HET


<class 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
7
HET
HET


In [25]:
zeroArr = np.zeros((2,3))
print(zeroArr)

print()

oneArr = np.ones((1,1))
print(oneArr)

print()

rangeArr = np.arange(1,10)
print(rangeArr)

print()

linspaceArr = np.linspace(1,20,10)
print(linspaceArr)


[[0. 0. 0.]
 [0. 0. 0.]]

[[1.]]

[1 2 3 4 5 6 7 8 9]

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]
