In [8]:
import numpy as np

arr = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

# Slicing -> array_name[start : end : step]

print(arr) # whole arr

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [38]:
# row wise
print(arr[0]) # [1,2,3,4] -> only o row
print('****************************************************************************************************')
print(arr[1:3]) # [[ 5  6  7  8] [ 9 10 11 12]] -> 1 to 3
print('****************************************************************************************************')
print(arr[2::]) # [[ 9 10 11 12] [13 14 15 16]] -> 2 to end
print('****************************************************************************************************')
print(arr[:2:]) # [[1 2 3 4] [5 6 7 8]] -> start to 2
print('****************************************************************************************************')
print(arr[::2]) # [[ 1  2  3  4] [ 9 10 11 12]] -> 0 2 4 6 step wise
print('****************************************************************************************************')
print(arr[::-1]) # [[13 14 15 16] [ 9 10 11 12] [ 5  6  7  8] [ 1  2  3  4]] -> end to start reverse
print('****************************************************************************************************')
print(arr[::-2]) # [[13 14 15 16] [ 5  6  7  8]] -> end to start but with 2 step

[1 2 3 4]
****************************************************************************************************
[[ 5  6  7  8]
 [ 9 10 11 12]]
****************************************************************************************************
[[ 9 10 11 12]
 [13 14 15 16]]
****************************************************************************************************
[[1 2 3 4]
 [5 6 7 8]]
****************************************************************************************************
[[ 1  2  3  4]
 [ 9 10 11 12]]
****************************************************************************************************
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
****************************************************************************************************
[[13 14 15 16]
 [ 5  6  7  8]]


In [37]:
# column wise
print(arr[: , 0]) # [ 1  5  9 13] -> first column
print('****************************************************************************************************')
print(arr[: , -1])  # [ 4  8 12 16] -> last column
print('****************************************************************************************************')
print(arr[: , 1:3]) # [ 2  3] [ 6  7] [10 11] [14 15]] -> 1 to 3 columns
print('****************************************************************************************************')
print(arr[: , ::2]) # [[ 1  3] [ 5  7] [ 9 11] [13 15]] -> 0 to end column with 2 step
print('****************************************************************************************************')
print(arr[: , ::-1]) # [[ 4  3  2  1] [ 8  7  6  5] [12 11 10  9] [16 15 14 13]] -> reverse columns
print('****************************************************************************************************')
print(arr[: , ::-2]) # [[ 4  2] [ 8  6] [12 10] [16 14]] -> reverse with 2 step

[ 1  5  9 13]
****************************************************************************************************
[ 4  8 12 16]
****************************************************************************************************
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
****************************************************************************************************
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
****************************************************************************************************
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
****************************************************************************************************
[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [39]:
# row & column
print(arr[1:3 , 1:3]) #[[ 6  7] [10 11]] -> 1 to 3 row , 1 to 3 column
print('****************************************************************************************************')
print(arr[2:: , 2::]) # [[11 12] [15 16]] -> row 2 to  end , cols 2 to end

[[ 6  7]
 [10 11]]
****************************************************************************************************
[[11 12]
 [15 16]]


In [15]:
arr2 = np.array([[1,2,3,4] , [5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
print(arr2.shape)
print(arr2.size)

(2, 4)
8


In [25]:
# accessing values
print(arr2[0,1])
print(arr2[0][1])
print(arr2.item(0,1))

2
2
2


In [34]:
# 4. Access Specific Indices (Flattened)
print(np.take(arr2 , [0,3,6]))
print()
np.put(arr2 , [0,3,6] , [10,10,10])
print(arr2)

[10 10 10]

[[10  2  3 10]
 [ 5  6 10  8]]


In [48]:
 # Boolean Filtering , Range Condition , OR Condition , Unique Values
even = arr2[arr2 % 2 == 0]
print(even)
print('****************************************************************************************************')
print(arr2[arr2 > 5])
print('****************************************************************************************************')
print(arr2[(arr2 >5) & (arr2 % 2 == 0)])
print('****************************************************************************************************')
print(arr2[(arr2 >5) | (arr2 % 2 == 0)])
print('****************************************************************************************************')
print(np.unique(arr2))

[10  2 10  6 10  8]
****************************************************************************************************
[10 10  6 10  8]
****************************************************************************************************
[10 10  6 10  8]
****************************************************************************************************
[10  2 10  6 10  8]
****************************************************************************************************
[ 2  3  5  6  8 10]
