In [18]:
import numpy as np

arr = np.array([[1,2,3] , [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 🔥 FINAL CONCEPT SUMMARY
# Operation	             Purpose
# reshape	     -> change shape safely
# resize	     -> force shape (risky)
# transpose	     -> flip rows & columns
# swapaxes	     -> general axis swap
# flatten	     -> convert to 1D
# flatten('F')	 -> column-wise flatten
# sort(axis=1)	 -> row-wise sorting
# # sort(axis=0) ->	column-wise sorting


# 🚀 Real AI/ML Usage
# Concept	-> Real Use
# reshape	-> prepare data for model input
# flatten	-> convert image → vector
# transpose	-> matrix operations
# resize	-> rarely used (dangerous)
# sort	    -> ranking, preprocessing

In [20]:
# Reshaping (Change Shape without Changing Data)
# reshape() does NOT modify original array
# It returns a new array

print(arr.reshape((1,6)))

[[1 2 3 4 5 6]]


In [21]:
## Resize (Modify Original Array)
# ✔ Meaning:
# Force array into 2×5 shape

# Total elements needed = 10
# But original = 9 → NumPy will:

# Either repeat values OR add zeros

print(np.resize(arr , (2,5)))


[[1 2 3 4 5]
 [6 1 2 3 4]]


In [26]:
# Transpose (Flip Rows ↔ Columns)
print(arr)
print()
print(arr.transpose())

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [25]:
# Swap Axes
arr2 = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
print(arr2)
print()
print(arr2.swapaxes(0,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
# Flatten (Convert to 1D)
print(arr2.flatten())

[1 2 3 4 5 6 7 8 9]


In [28]:
# Flatten Column-wise
print(arr2.flatten('F'))

[1 4 7 2 5 8 3 6 9]


In [33]:
# Sorting Rows
sortarr = arr2.sort(axis=1)
print(sortarr)

None


In [34]:
# Sorting Columns
sortarr2 = arr2.sort(axis=0)
print(sortarr2)

None
