In [ ]:
# Stacking in NumPy is the process of joining a sequence of arrays (of the same shape) along a new axis, 
# resulting in a higher-dimensional array.

# Splitting in NumPy is the process of breaking a single array into multiple smaller sub-arrays along a specified axis,
# allowing for easier data manipulation.

# Function	     Purpose
# vstack	     -> stack vertically
# hstack	     -> stack horizontally
# delete	     -> remove rows/columns
# column_stack   ->	combine columns
# row_stack	     -> combine rows
# hsplit         ->	split columns

# 🚀 Real AI/ML Usage
# Operation	         Real Use
# vstack	   -> combine datasets
# hstack	   -> add features
# delete	   -> remove unwanted data
# split	       -> train-test split
# column_stack -> merge feature columns

In [3]:
import numpy as np
# Generating Random Arrays
arr1 = np.random.randint(10, size=(2, 2))
arr2 = np.random.randint(10, size=(2, 2))
print(arr1)
print(arr2)

[[6 2]
 [0 8]]
[[5 6]
 [0 0]]


In [5]:
# Vertical Stack (vstack)
print(np.vstack((arr1,arr2)))

[[6 2]
 [0 8]
 [5 6]
 [0 0]]


In [6]:
# Horizontal Stack (hstack)
print(np.hstack((arr1,arr2)))

[[6 2 5 6]
 [0 8 0 0]]


In [7]:
# Delete Rows
arr3 = np.delete(arr1 , 1 , 0) 
# Delete index 1 (2nd row)
# axis=0 → rows
print(arr3)

[[6 2]]


In [8]:
#  not imp Column Stack
# ✔ Similar to hstack, but handles 1D arrays better
print(np.column_stack((arr1,arr2)))

[[6 2 5 6]
 [0 8 0 0]]


In [9]:
# not imp Row Stack
print(np.row_stack((arr1,arr2)))

[[6 2]
 [0 8]
 [5 6]
 [0 0]]


C:\Users\Admin\AppData\Local\Temp\ipykernel_13528\687928731.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((arr1,arr2)))


In [11]:
arr = np.random.randint(10 , size=(2,10))
print(arr)

[[5 9 4 9 2 3 1 3 5 1]
 [2 8 5 6 8 5 9 5 4 9]]


In [14]:
# Horizontal Split (hsplit)
np.hsplit(arr , 5)

[array([[5, 9],
        [2, 8]], dtype=int32),
 array([[4, 9],
        [5, 6]], dtype=int32),
 array([[2, 3],
        [8, 5]], dtype=int32),
 array([[1, 3],
        [9, 5]], dtype=int32),
 array([[5, 1],
        [4, 9]], dtype=int32)]

In [15]:
# Split at specific indices.
np.hsplit(arr  , (2,4))

[array([[5, 9],
        [2, 8]], dtype=int32),
 array([[4, 9],
        [5, 6]], dtype=int32),
 array([[2, 3, 1, 3, 5, 1],
        [8, 5, 9, 5, 4, 9]], dtype=int32)]