In [3]:
import numpy as np
# 🚀 Real AI/ML Usage
# Concept	     Use
# exp	    -> softmax
# log       -> loss functions
# sum	    -> cost calculation
# argmax	-> prediction class
# random	-> initialize weights  

In [4]:
# Element-wise Arithmetic Operations
arr3 = np.array([1, 2, 3, 4])
arr4 = np.array([2, 4, 6, 8])

print(arr3 + arr4)   # [3 6 9 12]
print(arr3 - arr4)   # [-1 -2 -3 -4]
print(arr3 * arr4)  # [2 8 18 32]
print(arr3 / arr4)   # [0.5 0.5 0.5 0.5]

[ 3  6  9 12]
[-1 -2 -3 -4]
[ 2  8 18 32]
[0.5 0.5 0.5 0.5]


In [5]:
#Aggregate function -> Summarize data and return a single value

import numpy as np

arr = np.array([[1,2,3,4,5] ,
                [6,7,8,9,10]])

print(np.sum(arr)) # 55
print(np.sum(arr , axis=0)) # [ 7  9 11 13 15] -> sum colums wise
print(np.sum(arr , axis=1)) # [ 15 , 40] -> sum row wise
print('****************************************************************************************************')
print(np.max(arr)) # 10
print(np.min(arr)) # 1
print(np.argmax(arr)) # 9 (Index of max element)
print(np.argmin(arr)) # 0 (Index of min element)
print(np.mean(arr)) # 5.5 (Average)
print(np.median(arr)) # 5.5 (Medain of data)
print(np.std(arr)) # 2.8722813232690143 (Standard Deviation)
print(np.var(arr)) # 8.25 (Variance)

55
[ 7  9 11 13 15]
[15 40]
****************************************************************************************************
10
1
9
0
5.5
5.5
2.8722813232690143
8.25


In [6]:
print(np.add(arr3, arr4))
print(np.subtract(arr3, arr4))
print(np.multiply(arr3, arr4))
print(np.divide(arr3, arr4))
print(np.remainder(arr3, arr4))
print(np.power(arr3, arr4))

[ 3  6  9 12]
[-1 -2 -3 -4]
[ 2  8 18 32]
[0.5 0.5 0.5 0.5]
[1 2 3 4]
[    1    16   729 65536]


In [7]:
print(np.sqrt(arr3))
print(np.cbrt(arr3))
print(np.absolute([-1, -2]))
print(np.exp(arr3))


[1.         1.41421356 1.73205081 2.        ]
[1.         1.25992105 1.44224957 1.58740105]
[1 2]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [8]:
print(np.log(arr3))
print(np.log2(arr3))
print(np.log10(arr3))
print(np.gcd.reduce([9, 12, 15]))  # 3
print(np.lcm.reduce([9, 12, 15]))  # 180

[0.         0.69314718 1.09861229 1.38629436]
[0.        1.        1.5849625 2.       ]
[0.         0.30103    0.47712125 0.60205999]
3
180


In [9]:
arr = np.array([[1,2,3,4,5] ,
                [6,7,8,9,10]])
print(np.count_nonzero(arr)) # 10 (Count non zero element)
print(np.prod(arr)) # 3628800 (Product of all element)
print(np.cumsum(arr)) # [ 1  3  6 10 15 21 28 36 45 55] (Cumulative Sum)
print(np.cumprod(arr)) #[ 1  2  6  24  120  720  5040  40320  362880  3628800] (Cumulative Product)
print(np.ptp(arr)) # 9 (max - min (Peak-to-Peak))
print(np.any(arr > 50))  # False -> True if any value > 5
print(np.all(arr > 0))  # True -> True if all positive
print(np.where(arr > 3))
narrr = np.where(arr > 5, 100, arr)
print(narrr)

10
3628800
[ 1  3  6 10 15 21 28 36 45 55]
[      1       2       6      24     120     720    5040   40320  362880
 3628800]
9
False
True
(array([0, 0, 1, 1, 1, 1, 1]), array([3, 4, 0, 1, 2, 3, 4]))
[[  1   2   3   4   5]
 [100 100 100 100 100]]


In [10]:
# A percentile tells you the value below which a given % of data falls.
# 25th percentile (Q1) → 25% data below this value
# 50th percentile (Q2 / Median) → middle value
# 75th percentile (Q3) → 75% data below this value
print(np.percentile(arr, 25))  # 3.25
print(np.percentile(arr, 50))  # 5.5
print(np.percentile(arr, 75))  # 7.75

3.25
5.5
7.75


In [11]:
# Argmax
# Returns index of max value per column
# Argmin 
# Gives index of minimum values
print(arr3.argmax(axis = 0))
print(arr3.argmin(axis = 0))

3
0


In [12]:
# Clip Limits values between min & max
print(np.clip(arr3, 2, 3))

[2 2 3 3]


In [13]:
# Dot Product
print(np.dot(arr3 , arr4))

60


In [14]:
# Matrix Multiplication
print(np.matmul(arr3,arr4))

60


In [15]:
# Correlation
print(np.corrcoef(arr3,arr4))

[[1. 1.]
 [1. 1.]]
