# 🧠 NumPy Practice Problems — ML Focused
All problems use NumPy. Each cell contains the problem, input, your solution space, and expected output in comments.

In [23]:
import numpy as np

---
## 🧠 Problem 1: Normalize Data (VERY IMPORTANT)
**Formula:** `(x - mean) / std`

In [24]:
# Input
arr = np.array([10, 20, 30, 40, 50])

# Task: Normalize using (x - mean) / std

# YOUR CODE HERE
normalized = (arr - arr.mean()) / arr.std()

print(normalized)

# Expected Output (approx):
# [-1.414, -0.707,  0.0,   0.707,  1.414]

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


---
## 🧠 Problem 2: Feature Filtering
**Task:** Get only values greater than 10

In [25]:
# Input
arr = np.array([5, 12, 7, 18, 3])

# Task: Get values > 10

# YOUR CODE HERE
filtered = arr[arr>10]

print(filtered)

# Expected Output:
# [12, 18]

[12 18]


---
## 🧠 Problem 3: Replace Outliers
**Task:** Replace values > 10 with the mean of the entire array

In [26]:
# Input
arr = np.array([1, 2, 100, 3, 4])

# Task: Replace values > 10 with mean of the array

# YOUR CODE HERE
mean_val = arr.mean()
arr_replaced = np.where(arr > 10 , mean_val , arr)

print(arr_replaced)

# Expected Output:
# [ 1  2  22  3  4]

[ 1.  2. 22.  3.  4.]


---
## 🧠 Problem 4: Dot Product (ML Core)
**Task:** Compute the dot product of two vectors

In [27]:
# Input
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Task: Compute dot product

# YOUR CODE HERE
dot = np.dot(a,b)

print(dot)

# Expected Output:
# 32

32


---
## 🧠 Problem 5: Matrix Multiplication
**Task:** Multiply two 2x2 matrices using `@` operator

In [28]:
# Input
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Task: Compute A @ B

# YOUR CODE HERE
result = np.matmul(A,B)

print(result)

# Expected Output:
# [[19, 22],
#  [43, 50]]

[[19 22]
 [43 50]]


---
## 🧠 Problem 6: Column-wise Mean
**Task:** Find the mean of each column in a 2D array

In [29]:
# Input
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Task: Find mean of each column (axis=0)

# YOUR CODE HERE
col_means = arr.mean(axis = 0)

print(col_means)

# Expected Output:
# [2.5, 3.5, 4.5]

[2.5 3.5 4.5]


---
## 🧠 Problem 7: One-Hot Encoding (Basic ML)
**Task:** Convert class labels to one-hot encoded matrix

In [30]:
# Input
arr = np.array([0, 1, 2])

# Task: Convert to one-hot encoding

# YOUR CODE HERE
one_hot = np.eye(3)[arr]

print(one_hot)

# Expected Output:
# [[1, 0, 0],
#  [0, 1, 0],
#  [0, 0, 1]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


---
## 🧠 Problem 8: Find Index of Max Value per Column
**Task:** Return the row index of the maximum value in each column

In [31]:
# Input
arr = np.array([[10, 20, 30],
                [40, 15, 25]])

# Task: Find index of max value in each column (axis=0)

# YOUR CODE HERE
max_indices = arr.argmax(axis = 0)

print(max_indices)

# Expected Output:
# [1, 0, 0]

[1 0 0]


---
## 🧠 Problem 9: Standard Deviation & Variance
**Task:** Compute both std and variance of the array

In [32]:
# Input
arr = np.array([2, 4, 6, 8])

# Task: Find standard deviation and variance

# YOUR CODE HERE
std = arr.std()
var = arr.var()

print(f"std = {std:.3f}")
print(f"var = {var:.1f}")

# Expected Output:
# std = 2.236
# var = 5.0

std = 2.236
var = 5.0


---
## 🧠 Problem 10: Apply Condition (np.where)
**Task:** Replace values greater than 5 with 100 using `np.where`

In [33]:
# Input
arr = np.array([1, 6, 3, 8])

# Task: Replace values > 5 with 100

# YOUR CODE HERE
result = np.where(arr > 5 , 100 , arr)

print(result)

# Expected Output:
# [  1, 100,   3, 100]

[  1 100   3 100]


---
## 🔥 BONUS — Interview Level: Predict the Output
**Task:** Without running the code, predict what `np.sum(arr, axis=0)` returns

In [34]:
# Input
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Task: Predict the output BEFORE running!
# axis=0 → sum along rows (column-wise)

# YOUR PREDICTION: ?

output = np.sum(arr, axis=0)
print(output)

# Expected Output:
# [5, 7, 9]
#
# Explanation:
# col0: 1 + 4 = 5
# col1: 2 + 5 = 7
# col2: 3 + 6 = 9

[5 7 9]
